In [18]:
import numpy as np

In [19]:
A =  np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [20]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [21]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [58]:
a = np.random.randn(5, 1)
assert(a.shape == (5,1))
print(a)
print(a.shape)
print(a.T)
print(np.dot(a, a.T))
v = np.array([[1,2]])
# m = np.dot(v,v)
y = v*v
print(y)


[[-0.3526838 ]
 [-0.45355989]
 [-0.91265435]
 [ 0.41809411]
 [ 0.54693166]]
(5, 1)
[[-0.3526838  -0.45355989 -0.91265435  0.41809411  0.54693166]]
[[ 0.12438587  0.15996323  0.32187841 -0.14745502 -0.19289394]
 [ 0.15996323  0.20571657  0.41394341 -0.18963072 -0.24806627]
 [ 0.32187841  0.41394341  0.83293795 -0.3815754  -0.49915956]
 [-0.14745502 -0.18963072 -0.3815754   0.17480268  0.22866891]
 [-0.19289394 -0.24806627 -0.49915956  0.22866891  0.29913424]]
[[1 4]]
